### PR TITLE
Allow wrapping arrays with options

### LINKED ISSUE #88: potential bug: `wrap` now autostarting iterators that were previously not autostarted prior to optimisation work
Placeholder - will try create a minimal example or debug tommorow :)

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Fixes https://github.com/RubenVerborgh/AsyncIterator/issues/88

### CODE REVIEW

**Comment by jacoscaz** [comment]
Yup, +1 from me!

**Comment by jeswr** [comment]
@RubenVerborgh - I also think w need to be closing the wrapping iterator here https://github.com/RubenVerborgh/AsyncIterator/blob/915a85734824809cc65b189d3e095c590da1334b/asynciterator.ts#L2031 (otherwise the iterator is permanently open if the promise rejects).

**Comment by RubenVerborgh** [comment]
@jeswr We probably need a better strategy around `error`. At the moment, I consider an iterator that has emitted an `error` as unpredictable and unusable. Perhaps we need a separated `errored` state. I'd leave that as a todo in https://github.com/RubenVerborgh/AsyncIterator/issues/92

**Review by jeswr — APPROVED** [review]

**Comment by RubenVerborgh** [comment]
Thank you!

**Pull request merged**
