### PR TITLE
Adds destroySource support to wrap() and WrappingIterator

### LINKED ISSUE #83: WrappingIterator does not destroy sources
Unlike other iterators, the new WrappingIterator does not destroy sources on end, nor has it a `destroySource` option.

This will likely result in problems where iterators keep running internally for a while (or infinitely), even though they can be stopped.

### PR DESCRIPTION
**Pull request by jacoscaz**
Closes #83

### CODE REVIEW

**Review by rubensworks — APPROVED** [review]
LGTM!

Just noting that since WrappingIterator doesn't support `autoStart: false`, it won't be picked up yet by Comunica.

**Comment by jacoscaz** [comment]
@rubensworks I guess `WrappingIterator` implicitly behaves as if `autoStart` is always set to `false`. Perhaps we can make it so that if only `autoStart: false` is passed we can return a `WrappingIterator` instead of a `TransformIterator`?

**Comment by rubensworks** [comment]
> I guess WrappingIterator implicitly behaves as if autoStart is always set to false

Not sure, at first glance it looks to me like `source` is immediately being set, and things like listeners are being attached.
I suspect some more changes would have to be made, similar to `TransformIterator`.

**Comment by jacoscaz** [comment]
@rubensworks I think I've done it in https://github.com/RubenVerborgh/AsyncIterator/pull/85/commits/80fb650d7b06274ed80c61e0194a11a95b2621e7 but we can rollback if it doesn't look right.

**Comment by jacoscaz** [comment]
Mh... Nope, nevermind. I tested it with one project before pushing but it did break another. I'll rollback and consider this PR complete. We can address this separately.

**Comment by jeswr** [comment]
>  I'll rollback and consider this PR complete. We can address this separately.

bump @RubenVerborgh ?

**Comment by RubenVerborgh** [comment]
Thanks @jacoscaz, great work!

**Pull request merged**
