### PR TITLE
Backs BufferedIterator with a linked-list instead of an array

### PR DESCRIPTION
**Pull request by jacoscaz**
While researching and testing potential improvements for #44 and #38 I stumbled into a ~10% performance improvement from changing `BufferedIterator` so that it is backed by a linked-list instead of an array. 

This should not be the case, given https://github.com/RubenVerborgh/AsyncIterator/issues/38#issuecomment-1047549674:

> All major JavaScript engines implement behavior that is closer to O(1), see:
> 
> https://lannonbr.com/blog/2020-01-27-shift-optimizations
> https://bugzilla.mozilla.org/show_bug.cgi?id=1348772
> https://github.com/frida/v8/blob/main/src/builtins/array-shift.tq

However, it does seem to be the case in Node.js 14.x, 16.x and 17.x based on experimental data. @jeswr has raised the issue on the V8 repo https://bugs.chromium.org/p/v8/issues/detail?id=12730 .

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Great work, thanks!

I'm surprised it would only be 10% though, if the non-const behavior of Array shifting is indeed what is holding us back.
What measurements do you have?

**Comment by jacoscaz** [comment]
I'm timing the following while consuming a pre-generated array of `200000` items:

```typescript
const elapsed = await time((arr) => {
    let iterator: AsyncIterator<number> = new RangeIterator(arr);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    iterator = new TransformIterator(iterator);
    return iterator;
  });
```

I seem to be consistently getting ~580ms for the NPM version (array) and ~530ms for this version (linked-list).

> I'm surprised it would only be 10% though, if the non-const behavior of Array shifting is indeed what is holding us back.
> What measurements do you have?

I am surprised by this, too. I had expected a significantly larger difference. Likely this is just one factor in a number of factors that, when combined, result in more appreciable gains. Happy with leaving this open for a while as we do more testing.

EDIT: I'm testing on a 2020 13'' MacBook Pro (Apple Silicon, M1, 16 GB RAM).

**Comment by RubenVerborgh** [comment]
Thanks! Yes, more testing material would be useful. I think this particular case might just get highly optimized by V8, can we try it with some of the cases of the other issue?

Minor: I wonder if instead of `next?: LinkedNode<V>`, we might want to keep it monomorphic by having `next: LinkedNode<V>` where `tail` points to itself. (In any case I'd recommend `null` over `undefined`.)

**Comment by jacoscaz** [comment]
> In any case I'd recommend null over undefined.

Done!

>  I wonder if instead of next?: LinkedNode<V>, we might want to keep it monomorphic by having next: LinkedNode<V> where tail points to itself.

How would you do this? Can you even initialize a JS object with a property that points to itself?

**Comment by RubenVerborgh** [comment]
@jacoscaz I have no idea where the 10% came from, but I currently have

```javascript
console.time('BufferedIterator');
const it = new BufferedIterator();
for (let i = 0; i < 500_000; i++)
  it._push(i);
it.close();

it.on('data', () => null)
  .on('end', () => console.timeEnd('BufferedIterator'));
```

running at 33.9s with the array implementation, and 0.070s with your linked list, which is a 500x speed-up 😄

**Comment by jacoscaz** [comment]
>  which is a 500x speed-up

Ha! Nice! I must have messed up something in my testing. This is coherent with the findings in #47 . Thanks for having a look and merging so quickly!

**Comment by RubenVerborgh** [comment]
Thanks! This PR is now part of v3.4.0.

**Pull request merged**
