### PR TITLE
Fix bug in https://github.com/RubenVerborgh/AsyncIterator/issues/30

### PR DESCRIPTION
**Pull request by jeswr**
Resolve bug with missing overload declaration.

I don't have time to test this now - I can create a PR that converts the test suite to TS and so can properly apply tests to this change if you would like me to do that first (I can do this within the next 24 hrs)

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@rubensworks ok?

**Comment by rubensworks** [comment]
Yes, this fixes the problem. Thanks @jeswr!

**Comment by jeswr** [comment]
@RubenVerborgh  I'm in the process of moving the test suite to TS as mentioned above. Is it ok if I migrate it to use Jest at the same time (it will make the process easier)?

**Comment by RubenVerborgh** [comment]
@jeswr Be my guest but… I expect that to be a substantial amount of work. Especially with timing issues etc.

**Comment by jeswr** [comment]
> I expect that to be a substantial amount of work. Especially with timing issues etc.

It is a bit, so it's a WIP here https://github.com/jeswr/AsyncIterator/tree/chore/tests-to-typescript.

In the meantime, I have added the `FilterTypeTest.ts` file which tests that both versions of the overload work (if there is a type error then there will be an error when the test suite is run), so this AFAIK this should be safe to merge.

**Comment by RubenVerborgh** [comment]
Super, thank you!

**Comment by RubenVerborgh** [comment]
This somehow removes it from the docs though: https://github.com/RubenVerborgh/AsyncIterator/commit/d3f24be62e16d26d6f4c445b46bb75fb3072882e

**Pull request merged**
